# Introduction to decision-analytic models {#decision}

## Pre-session readings

Chapter 3 of *R for data science*.

**Economic evaluation**

*Gray, A. M., Clarke, P. M., Wolstenholme, J. L., & Wordsworth, S. (2011). Applied methods of cost-effectiveness analysis in healthcare (Vol. 3). Oxford University Press.* Chapter 2. 

*Birch, S., & Gafni, A. (1992). Cost effectiveness/utility analyses: do current decision rules lead us to where we want to be?. Journal of health economics, 11(3), 279-296.* 
*Doubilet, P., Weinstein, M. C., & McNeil, B. J. (1986). Use and misuse of the term “cost effective” in medicine.*

**Decision modelling**

*Briggs, A., Sculpher, M., & Claxton, K. (2006). Decision modelling for health economic evaluation. Oxford University Press.* Chapter 2. Sections 2.1 and 2.2

*Gray, A. M., Clarke, P. M., Wolstenholme, J. L., & Wordsworth, S. (2011). Applied methods of cost-effectiveness analysis in healthcare (Vol. 3). Oxford University Press.* Chapter 2. Sections 8.1 to 8.4

*Buxton, M. J., Drummond, M. F., Van Hout, B. A., Prince, R. L., Sheldon, T. A., Szucs, T., & Vray, M. (1997). Modelling in ecomomic evaluation: an unavoidable fact of life. Health economics, 6(3), 217-227.*

## Economic evaluation

Cost-effectiveness analysis (CEA) and cost-utility analysis (CUA) have been proposed as methods for comparing alternative uses of scarce health-care resources. The difference between CEA and CUA lies in the way outputs are measured.

We can find different objectives of CEA across the literature:

*"The underlying premise of cost-effectiveness analysis in health problems is that for any given level of resources available, society (or the decision making jurisdiction involved) wishes to maximize the total aggregate health benefits conferred"* @weinstein1977foundations.

*"For any given rate of output [the combination of inputs] . that costs the decision maker least"* @culyer1980political

*"a method of determining the most efficient way of dealing with a specified health problem"* @green1988priority

The goal of CEA is to maximize health benefits produced from a given level of resources. Therefore, it is consistent with welfare economics concept of Pareto efficiency [@birch1992cost] (Fig).

In practice, CEA **relaxes the constraint on available resources**. Because the focus of the evaluation is not a fixed resource pool, but a specific programme making demands on resources, the comparison of the programme under evaluation with an existing programme (e.g., services aimed at improving FS) must consider not only the inter-programme differences in outputs (incremental benefits), but also the inter-programme differences in resources used (incremental costs). 

Weinstein and Stason (1977) state that: *"the criterion for cost-effectiveness is the ratio of the net increase of health-care costs to the net effectiveness. The lower the value of this ratio, the higher the priority in terms of maximizing benefits derived from a given health expenditure"*. Issue is that applying a ratio does nod lead to the maximization of benefits from a fixed resource pool (movement from A to C in Figure). **The real problem of the application of CEA is the failure to adhere strictly to the notion of opportunity cost in the measurement of the (incremental) cost of a programme.** The existing programme represents a true opportunity cost for the entire resource requirements of the new programme, even though it does not absorb this level of resources.

### Cost-effectiveness in practive

As mentioned before, CEA include both costs and effects, which are represented graphically in a plane:

*Figura*






