<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Introduction to R | Advanced decision modelling in the context of Health Technology Assessment</title>
  <meta name="description" content="Introduction to R | Advanced decision modelling in the context of Health Technology Assessment" />
  <meta name="generator" content="bookdown 0.24 and GitBook 2.6.7" />

  <meta property="og:title" content="Introduction to R | Advanced decision modelling in the context of Health Technology Assessment" />
  <meta property="og:type" content="book" />
  
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Introduction to R | Advanced decision modelling in the context of Health Technology Assessment" />
  
  
  

<meta name="author" content="Juan Pablo Diaz Martinez" />


<meta name="date" content="2021-12-16" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="assignments.html"/>
<link rel="next" href="references.html"/>
<script src="libs/header-attrs-2.11/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Advanced decision modelling in HTA</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Introduction</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#why-reimbursment-submissions-fail"><i class="fa fa-check"></i>Why reimbursment submissions fail?</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#topics-of-the-course"><i class="fa fa-check"></i>Topics of the course</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#statistical-computing"><i class="fa fa-check"></i>Statistical computing</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#evaluation"><i class="fa fa-check"></i>Evaluation</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#asssignments"><i class="fa fa-check"></i>Asssignments</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#project-proposal"><i class="fa fa-check"></i>Project proposal</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#project-presentation"><i class="fa fa-check"></i>Project presentation</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#final-project"><i class="fa fa-check"></i>Final project</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#bibliography"><i class="fa fa-check"></i>Bibliography</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="HTA.html"><a href="HTA.html"><i class="fa fa-check"></i><b>1</b> What is HTA?</a>
<ul>
<li class="chapter" data-level="1.1" data-path="HTA.html"><a href="HTA.html#pre-session-readings"><i class="fa fa-check"></i><b>1.1</b> Pre-session readings</a></li>
<li class="chapter" data-level="1.2" data-path="HTA.html"><a href="HTA.html#definition-and-rationale"><i class="fa fa-check"></i><b>1.2</b> Definition and rationale</a></li>
<li class="chapter" data-level="1.3" data-path="HTA.html"><a href="HTA.html#hta-process"><i class="fa fa-check"></i><b>1.3</b> HTA process</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="HTA.html"><a href="HTA.html#identification-and-prioritization-of-technologies"><i class="fa fa-check"></i><b>1.3.1</b> Identification and prioritization of technologies</a></li>
<li class="chapter" data-level="1.3.2" data-path="HTA.html"><a href="HTA.html#clear-specification-of-the-problem"><i class="fa fa-check"></i><b>1.3.2</b> Clear specification of the problem</a></li>
<li class="chapter" data-level="1.3.3" data-path="HTA.html"><a href="HTA.html#technology-assessment-and-review"><i class="fa fa-check"></i><b>1.3.3</b> Technology assessment and review</a></li>
<li class="chapter" data-level="1.3.4" data-path="HTA.html"><a href="HTA.html#dissemination-of-recommendations"><i class="fa fa-check"></i><b>1.3.4</b> Dissemination of recommendations</a></li>
<li class="chapter" data-level="1.3.5" data-path="HTA.html"><a href="HTA.html#monitoring-the-impact-of-reports"><i class="fa fa-check"></i><b>1.3.5</b> Monitoring the impact of reports</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="HTA.html"><a href="HTA.html#excercises"><i class="fa fa-check"></i><b>1.4</b> Excercises</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="decision.html"><a href="decision.html"><i class="fa fa-check"></i><b>2</b> Introduction to decision-analytic models</a>
<ul>
<li class="chapter" data-level="2.1" data-path="decision.html"><a href="decision.html#pre-session-readings-1"><i class="fa fa-check"></i><b>2.1</b> Pre-session readings</a></li>
<li class="chapter" data-level="2.2" data-path="decision.html"><a href="decision.html#economic-evaluation-1"><i class="fa fa-check"></i><b>2.2</b> Economic evaluation</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="decision.html"><a href="decision.html#cost-effectiveness-in-practice"><i class="fa fa-check"></i><b>2.2.1</b> Cost-effectiveness in practice</a></li>
<li class="chapter" data-level="2.2.2" data-path="decision.html"><a href="decision.html#conclusions"><i class="fa fa-check"></i><b>2.2.2</b> Conclusions</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="decision.html"><a href="decision.html#decision-modelling"><i class="fa fa-check"></i><b>2.3</b> Decision modelling</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="decision.html"><a href="decision.html#importance-of-decision-analytic-models-in-hta"><i class="fa fa-check"></i><b>2.3.1</b> Importance of decision-analytic models in HTA</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="decision.html"><a href="decision.html#excercises-1"><i class="fa fa-check"></i><b>2.4</b> Excercises</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="tree.html"><a href="tree.html"><i class="fa fa-check"></i><b>3</b> Good practices in decision modelling and decion-tree models</a>
<ul>
<li class="chapter" data-level="3.1" data-path="tree.html"><a href="tree.html#pre-session-readings-2"><i class="fa fa-check"></i><b>3.1</b> Pre-session readings</a></li>
<li class="chapter" data-level="3.2" data-path="tree.html"><a href="tree.html#good-practices-in-decision-modelling"><i class="fa fa-check"></i><b>3.2</b> Good practices in decision modelling</a></li>
<li class="chapter" data-level="3.3" data-path="tree.html"><a href="tree.html#decision-tree-models"><i class="fa fa-check"></i><b>3.3</b> Decision-tree models</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="tree.html"><a href="tree.html#structure-and-order"><i class="fa fa-check"></i><b>3.3.1</b> Structure and order</a></li>
<li class="chapter" data-level="3.3.2" data-path="tree.html"><a href="tree.html#probabilities-in-a-tree"><i class="fa fa-check"></i><b>3.3.2</b> Probabilities in a tree</a></li>
<li class="chapter" data-level="3.3.3" data-path="tree.html"><a href="tree.html#payoffs"><i class="fa fa-check"></i><b>3.3.3</b> Payoffs</a></li>
<li class="chapter" data-level="3.3.4" data-path="tree.html"><a href="tree.html#expected-value"><i class="fa fa-check"></i><b>3.3.4</b> Expected value</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="markov.html"><a href="markov.html"><i class="fa fa-check"></i><b>4</b> Markov models</a>
<ul>
<li class="chapter" data-level="4.1" data-path="markov.html"><a href="markov.html#pre-session-readings-3"><i class="fa fa-check"></i><b>4.1</b> Pre-session readings</a></li>
<li class="chapter" data-level="4.2" data-path="markov.html"><a href="markov.html#introduction-1"><i class="fa fa-check"></i><b>4.2</b> Introduction</a></li>
<li class="chapter" data-level="4.3" data-path="markov.html"><a href="markov.html#best-practices"><i class="fa fa-check"></i><b>4.3</b> Best practices</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="evidence.html"><a href="evidence.html"><i class="fa fa-check"></i><b>5</b> Evidence synthesis</a>
<ul>
<li class="chapter" data-level="5.1" data-path="evidence.html"><a href="evidence.html#pre-session-readings-4"><i class="fa fa-check"></i><b>5.1</b> Pre-session readings</a></li>
<li class="chapter" data-level="5.2" data-path="evidence.html"><a href="evidence.html#identifying-aggregating-and-appraising-the-evidence"><i class="fa fa-check"></i><b>5.2</b> Identifying, aggregating and appraising the evidence</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="evidence.html"><a href="evidence.html#identifying-the-evidence"><i class="fa fa-check"></i><b>5.2.1</b> Identifying the evidence</a></li>
<li class="chapter" data-level="5.2.2" data-path="evidence.html"><a href="evidence.html#how-to-search"><i class="fa fa-check"></i><b>5.2.2</b> How to search</a></li>
<li class="chapter" data-level="5.2.3" data-path="evidence.html"><a href="evidence.html#aggregating-and-appraising-the-evidence"><i class="fa fa-check"></i><b>5.2.3</b> Aggregating and appraising the evidence</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="assignments.html"><a href="assignments.html"><i class="fa fa-check"></i>Assignments</a>
<ul>
<li class="chapter" data-level="" data-path="assignments.html"><a href="assignments.html#assignment-1"><i class="fa fa-check"></i>Assignment 1</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="introduction-to-r.html"><a href="introduction-to-r.html"><i class="fa fa-check"></i>Introduction to R</a>
<ul>
<li class="chapter" data-level="" data-path="introduction-to-r.html"><a href="introduction-to-r.html#outline"><i class="fa fa-check"></i>Outline</a></li>
<li class="chapter" data-level="" data-path="introduction-to-r.html"><a href="introduction-to-r.html#babies-dataset"><i class="fa fa-check"></i>Babies Dataset</a>
<ul>
<li class="chapter" data-level="" data-path="introduction-to-r.html"><a href="introduction-to-r.html#loading-babies-dataset"><i class="fa fa-check"></i>Loading babies dataset</a></li>
<li class="chapter" data-level="" data-path="introduction-to-r.html"><a href="introduction-to-r.html#data-manipulation"><i class="fa fa-check"></i>Data manipulation</a></li>
<li class="chapter" data-level="" data-path="introduction-to-r.html"><a href="introduction-to-r.html#creating-some-new-variables"><i class="fa fa-check"></i>Creating some new variables</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="introduction-to-r.html"><a href="introduction-to-r.html#functions"><i class="fa fa-check"></i>Functions</a>
<ul>
<li class="chapter" data-level="" data-path="introduction-to-r.html"><a href="introduction-to-r.html#built-in-functions"><i class="fa fa-check"></i>Built in Functions</a></li>
<li class="chapter" data-level="" data-path="introduction-to-r.html"><a href="introduction-to-r.html#user-defined-functions"><i class="fa fa-check"></i>User Defined Functions</a></li>
<li class="chapter" data-level="" data-path="introduction-to-r.html"><a href="introduction-to-r.html#saving-output-and-opening-in-word"><i class="fa fa-check"></i>Saving output and opening in word</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="introduction-to-r.html"><a href="introduction-to-r.html#working-with-more-than-one-dataset"><i class="fa fa-check"></i>Working with more than one dataset</a></li>
<li class="chapter" data-level="" data-path="introduction-to-r.html"><a href="introduction-to-r.html#matrices"><i class="fa fa-check"></i>Matrices</a></li>
<li class="chapter" data-level="" data-path="introduction-to-r.html"><a href="introduction-to-r.html#lists"><i class="fa fa-check"></i>Lists</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Advanced decision modelling in the context of Health Technology Assessment</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="introduction-to-r" class="section level1 unnumbered">
<h1>Introduction to R</h1>
<p>The goal of this tutorial is to orient the learner to R Studio and the R programming language.</p>
<p>Please complete the following:</p>
<ol style="list-style-type: decimal">
<li>Create a folder somewhere you can easily find it (e.g., on your desktop) called ‘R Course.’</li>
<li>Open R Studio</li>
<li>Session -&gt; Set Working Directory -&gt; to source file location</li>
</ol>
<div id="outline" class="section level2 unnumbered">
<h2>Outline</h2>
<ol style="list-style-type: decimal">
<li>Read in the ‘babies’ data set</li>
<li>Basic data manipulation</li>
<li>Functions</li>
<li>Saving and viewing results</li>
</ol>
</div>
<div id="babies-dataset" class="section level2 unnumbered">
<h2>Babies Dataset</h2>
<p>The <code>babies</code> dataset will be used throughout this session to illustrate basic R concepts.</p>
<p>The dataset is a collection of variables taken for each new mother in a Child and Health Development Study. It has 1,236 observations on male live births for the following 23 variables.</p>
<p>Variables in data file</p>
<pre><code>id            identification number
date          birth date as character string (mon-dd-yyyy)
ddate         day of birth
mdate         month of birth
ydate         year of birth
gestation     length of gestation in days
wt            birth weight in ounces (999 unknown)
parity        total number of previous pregnancies 
              including fetal deaths and still births
age           mother&#39;s age in years at end of pregnancy
                999=unknown
ed            mother&#39;s education 
                 0=less than 8th grade
                 1=8th-12th grade - did not graduate
                 2=HS graduate???no other schooling
                 3=HS+trade
                 4=HS+some college
                 5=College graduate,
                 6=Trade school HS unclear
                 9=unknown
ht            mother&#39;s height in inches to the last completed inch 
                 999=unknown
wt1           mother prepregnancy wt in pounds
                 999=unknown
dage          father&#39;s age, coding same as mother&#39;s age.
ded           father&#39;s education, coding same as mother&#39;s education.
dht           father&#39;s height, coding same as for mother&#39;s height
dwt           father&#39;s weight coding same as for mother&#39;s weight
inc           family yearly income in $2500 increments
                 0=under 2500
                 1=2500-4999
                 ..., 
                 8= 12,500-14,999
                 9=15000+
                 998=unknown
                 999=not asked
smoke         does mother smoke? 
                 0=never
                 1=smokes now
                 2=until current pregnancy
                 3=once did, not now
                 9=unknown
time          If mother quit smoking, how long ago? 
                 0=never smoked
                 1=still smokes
                 2=during current preg
                 3=within 1 yr
                 4=1 to 2 years ago
                 5=2 to 3 years ago
                 6=3 to 4 years ago
                 7=5 to 9 years ago 
                 8=10+years ago
                 9=quit and don&#39;t know,
                 998=unknown
                 999=not asked
number        number of cigs smoked per day for past and current smokers 
                 0=never
                 1=1-4
                 2=5-9
                 3=10-14
                 4=15-19
                 5=20-29
                 6=30-39
                 7=40-60
                 8=60+
                 9=smoke but don&#39;t know
                 998=unknown
                 999=not asked
race          mother&#39;s race 
marital       marital status of mother
drace         father&#39;s race, coding same as mother&#39;s race</code></pre>
<div id="loading-babies-dataset" class="section level3 unnumbered">
<h3>Loading babies dataset</h3>
<p>We can can load the data from our working directory as shown below. It is a .csv file, so can be read in with <code>read.csv</code>. specifying that</p>
<ul>
<li>the file has a “header” row (<code>header=T</code>) with variable names</li>
<li>values are separated by commas.<br />
</li>
<li>values of ’‘, ’998’ or ‘999’ represent missing data</li>
</ul>
<p>We need to be confident that 998 and 999 are not legitimate values for any variables, so that R does not interpret legitimate values as missing. We will not distinguish between ‘unknown’ and ‘not asked’ in the data, so the code below will read two consecutive commas (``‘), 998, and 999 as missing values. We will have to deal separately with the values ’9’ that mean a value is missing.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="introduction-to-r.html#cb2-1" aria-hidden="true" tabindex="-1"></a>babies <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&#39;babies.csv&#39;</span>,<span class="at">header=</span>T, <span class="at">sep=</span><span class="st">&quot;,&quot;</span>, </span>
<span id="cb2-2"><a href="introduction-to-r.html#cb2-2" aria-hidden="true" tabindex="-1"></a>                     <span class="at">na.strings=</span><span class="fu">c</span>(<span class="st">&quot;&quot;</span>, <span class="st">&quot;998&quot;</span>, <span class="st">&quot;999&quot;</span>))</span></code></pre></div>
</div>
<div id="data-manipulation" class="section level3 unnumbered">
<h3>Data manipulation</h3>
<p>What are the dimensions of the data set?</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="introduction-to-r.html#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(babies)</span></code></pre></div>
<p>[1] 1236 23</p>
<p>What are the names of the variables?</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="introduction-to-r.html#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(babies)</span></code></pre></div>
<pre><code>##  [1] &quot;id&quot;        &quot;date&quot;      &quot;gestation&quot; &quot;wt&quot;        &quot;parity&quot;    &quot;age&quot;      
##  [7] &quot;ed&quot;        &quot;ht&quot;        &quot;wt1&quot;       &quot;dage&quot;      &quot;ded&quot;       &quot;dht&quot;      
## [13] &quot;dwt&quot;       &quot;inc&quot;       &quot;smoke&quot;     &quot;time&quot;      &quot;number&quot;    &quot;race&quot;     
## [19] &quot;marital&quot;   &quot;drace&quot;     &quot;ddate&quot;     &quot;mdate&quot;     &quot;ydate&quot;</code></pre>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="introduction-to-r.html#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co">#head(babies)</span></span>
<span id="cb6-2"><a href="introduction-to-r.html#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="co">#tail(babies)</span></span></code></pre></div>
<p>Isolating variables</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="introduction-to-r.html#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># babies$id</span></span>
<span id="cb7-2"><a href="introduction-to-r.html#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="co"># babies[, 1]</span></span>
<span id="cb7-3"><a href="introduction-to-r.html#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="co"># babies[, &#39;id&#39;]</span></span>
<span id="cb7-4"><a href="introduction-to-r.html#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="co"># babies[1:10, c(&#39;id&#39;, &#39;date&#39;, &#39;gestation&#39;)]</span></span></code></pre></div>
<p>Assignment and subsetting</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="introduction-to-r.html#cb8-1" aria-hidden="true" tabindex="-1"></a>under<span class="fl">.30</span><span class="ot">&lt;-</span> babies<span class="sc">$</span>age<span class="sc">&lt;</span><span class="dv">30</span></span>
<span id="cb8-2"><a href="introduction-to-r.html#cb8-2" aria-hidden="true" tabindex="-1"></a>b<span class="ot">&lt;-</span> babies[under<span class="fl">.30</span>, ]</span>
<span id="cb8-3"><a href="introduction-to-r.html#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(b<span class="sc">$</span>age)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA&#39;s 
##   15.00   22.00   24.00   24.03   27.00   29.00       2</code></pre>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="introduction-to-r.html#cb10-1" aria-hidden="true" tabindex="-1"></a>b<span class="ot">&lt;-</span> babies[<span class="fu">which</span>(under<span class="fl">.30</span>), ]</span>
<span id="cb10-2"><a href="introduction-to-r.html#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(b<span class="sc">$</span>age)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   15.00   22.00   24.00   24.03   27.00   29.00</code></pre>
<div id="exercises-1" class="section level4 unnumbered">
<h4>Exercises (1)</h4>
<ol style="list-style-type: decimal">
<li><p>Create a new data set consisting of only the rows where the father’s age is 40 or over (use ‘&gt;=’)</p></li>
<li><p>Include only the mother’s age, father’s age and marital status in the new dataset</p></li>
<li><p>Display the dimensions of this data set in the console.</p></li>
<li><p>Locate the new dataset in th Global Environment and view it</p></li>
</ol>
<p>NB: Be sure that you have handled missing father’s ages properly</p>
<div id="exercises-1-solutions" class="section level5 unnumbered">
<h5>Exercises (1) solutions</h5>
</div>
</div>
</div>
<div id="creating-some-new-variables" class="section level3 unnumbered">
<h3>Creating some new variables</h3>
<p>A baby weight more than 4kg is defined as macrosomia. We can create this variable (converting ounces to kg) as:</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="introduction-to-r.html#cb12-1" aria-hidden="true" tabindex="-1"></a>babies<span class="sc">$</span>wtKg <span class="ot">&lt;-</span> babies<span class="sc">$</span>wt<span class="sc">/</span>(<span class="dv">16</span><span class="sc">*</span><span class="fl">2.2</span>)</span>
<span id="cb12-2"><a href="introduction-to-r.html#cb12-2" aria-hidden="true" tabindex="-1"></a>babies<span class="sc">$</span>macrosomia <span class="ot">&lt;-</span> babies<span class="sc">$</span>wtKg <span class="sc">&gt;</span> <span class="dv">4</span></span></code></pre></div>
<p>A baby weighing less than 2.5kg is defined as “small.” We can create this variable as:</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="introduction-to-r.html#cb13-1" aria-hidden="true" tabindex="-1"></a>babies<span class="sc">$</span>smallBaby <span class="ot">&lt;-</span> babies<span class="sc">$</span>wtKg <span class="sc">&lt;</span> <span class="fl">2.5</span></span></code></pre></div>
<p>We can make a single character variable with three categories of weight:</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="introduction-to-r.html#cb14-1" aria-hidden="true" tabindex="-1"></a>babies<span class="sc">$</span>birthWeightCat <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(babies<span class="sc">$</span>wtKg <span class="sc">&lt;</span> <span class="fl">2.5</span>, <span class="st">&quot;small&quot;</span>,</span>
<span id="cb14-2"><a href="introduction-to-r.html#cb14-2" aria-hidden="true" tabindex="-1"></a>                                <span class="fu">ifelse</span>(babies<span class="sc">$</span>wtKg <span class="sc">&gt;</span> <span class="dv">4</span>, <span class="st">&quot;large&quot;</span>,<span class="st">&quot;normal&quot;</span>))</span></code></pre></div>
<p>Notice that when we tabulate these, they appear in alphabetical order.</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="introduction-to-r.html#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(babies<span class="sc">$</span>birthWeightCat)</span></code></pre></div>
<pre><code>## 
##  large normal  small 
##    145   1033     58</code></pre>
<p>To impose an order, we can convert to a factor and specify the order:</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="introduction-to-r.html#cb17-1" aria-hidden="true" tabindex="-1"></a>babies<span class="sc">$</span>birthWeightCat <span class="ot">&lt;-</span> <span class="fu">factor</span>(babies<span class="sc">$</span>birthWeightCat, </span>
<span id="cb17-2"><a href="introduction-to-r.html#cb17-2" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">levels=</span><span class="fu">c</span>(<span class="st">&quot;small&quot;</span>,<span class="st">&quot;normal&quot;</span>,<span class="st">&quot;large&quot;</span>),</span>
<span id="cb17-3"><a href="introduction-to-r.html#cb17-3" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">labels=</span><span class="fu">c</span>(<span class="st">&quot;Small baby&quot;</span>,<span class="st">&quot;Normal weight baby&quot;</span>,<span class="st">&quot;Large baby&quot;</span>))</span>
<span id="cb17-4"><a href="introduction-to-r.html#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(babies<span class="sc">$</span>birthWeightCat)                                </span></code></pre></div>
<pre><code>## 
##         Small baby Normal weight baby         Large baby 
##                 58               1033                145</code></pre>
<p>A baby born before 37 completed weeks of pregnancy is defined as preterm. We can create this logical variable as:</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="introduction-to-r.html#cb19-1" aria-hidden="true" tabindex="-1"></a>babies<span class="sc">$</span>preterm <span class="ot">&lt;-</span> babies<span class="sc">$</span>gestation <span class="sc">&lt;</span> <span class="dv">37</span><span class="sc">*</span><span class="dv">7</span></span>
<span id="cb19-2"><a href="introduction-to-r.html#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(babies<span class="sc">$</span>preterm)</span></code></pre></div>
<pre><code>## 
## FALSE  TRUE 
##  1126    97</code></pre>
<p>This is just a logical variable (<code>TRUE/FALSE</code> or <code>T/F</code>) so we need to make a factor to have it appear more user-friendly:</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="introduction-to-r.html#cb21-1" aria-hidden="true" tabindex="-1"></a>babies<span class="sc">$</span>whenBorn <span class="ot">&lt;-</span> <span class="fu">factor</span>(babies<span class="sc">$</span>preterm, </span>
<span id="cb21-2"><a href="introduction-to-r.html#cb21-2" aria-hidden="true" tabindex="-1"></a>                          <span class="at">levels=</span><span class="fu">c</span>(<span class="cn">TRUE</span>,<span class="cn">FALSE</span>), </span>
<span id="cb21-3"><a href="introduction-to-r.html#cb21-3" aria-hidden="true" tabindex="-1"></a>                          <span class="at">labels=</span><span class="fu">c</span>(<span class="st">&quot;Preterm&quot;</span>,<span class="st">&quot;Full-term&quot;</span>))</span></code></pre></div>
<p>We can make a binary variable for the mother’s and father’s races:</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="introduction-to-r.html#cb22-1" aria-hidden="true" tabindex="-1"></a>babies<span class="sc">$</span>whiteRace <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(babies<span class="sc">$</span>race<span class="sc">==</span><span class="st">&quot;white&quot;</span>,<span class="st">&quot;white&quot;</span>,<span class="st">&quot;other&quot;</span>)</span>
<span id="cb22-2"><a href="introduction-to-r.html#cb22-2" aria-hidden="true" tabindex="-1"></a>babies<span class="sc">$</span>dwhiteRace <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(babies<span class="sc">$</span>drace<span class="sc">==</span><span class="st">&quot;white&quot;</span>,<span class="st">&quot;white&quot;</span>,<span class="st">&quot;other&quot;</span>)</span></code></pre></div>
<div id="exercises-2" class="section level4 unnumbered">
<h4>Exercises (2)</h4>
<ol style="list-style-type: decimal">
<li>Starting with the numeric variable <code>smoke</code>, in the babies dataset, create a new variable <code>smokeCat</code> in the data set that has three levels: <code>never smoker</code>, <code>past smoker</code>,<code>current smoker</code>. Use the <code>factor</code> function and ensure that the levels appear in that order.</li>
<li>Tabulate the numerical variable against the new one to make sure you have not made an error.</li>
<li>Make a binary variable in the babies dataset <code>smokeNow</code> that is ‘Yes’ when the mother smokes and ‘No’ otherwise (i.e., it is not yes (1) or it is missing (9).)</li>
<li>[optional] Make a factor variable <code>eduCat</code> from the mother’s education variable <code>ed</code> using the information at the top if this file about the meaning of 1,2,3,…</li>
</ol>
<div id="exercises-2-solutions" class="section level5 unnumbered">
<h5>Exercises (2) solutions</h5>
<ol style="list-style-type: decimal">
<li><p>Make the two variables:</p></li>
<li><p>Check the coding was correct</p></li>
<li><p>Make a binary variable</p></li>
<li><p>[optional] make the education variable and check it</p></li>
</ol>
</div>
</div>
</div>
</div>
<div id="functions" class="section level2 unnumbered">
<h2>Functions</h2>
<p>Two types:</p>
<ol style="list-style-type: decimal">
<li>Built in functions</li>
<li>User defined functions</li>
</ol>
<div id="built-in-functions" class="section level3 unnumbered">
<h3>Built in Functions</h3>
<p>When you open R, there are many functions available to you: Here, we will review a few useful built in functions.</p>
<p>If you need help using a function, execute ? followed by the function name, with or without the parentheses.</p>
<pre><code>? table</code></pre>
<p>The following functions are widely used in descriptive statistics</p>
<div id="table-prop.table" class="section level4 unnumbered">
<h4>table(), prop.table()</h4>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="introduction-to-r.html#cb24-1" aria-hidden="true" tabindex="-1"></a>t<span class="ot">&lt;-</span> <span class="fu">with</span>(babies, <span class="fu">table</span>(marital))</span>
<span id="cb24-2"><a href="introduction-to-r.html#cb24-2" aria-hidden="true" tabindex="-1"></a>t</span></code></pre></div>
<pre><code>## marital
##          divorced legally separated           married     never married 
##                 5                15              1208                 6 
##           unknown 
##                 2</code></pre>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="introduction-to-r.html#cb26-1" aria-hidden="true" tabindex="-1"></a>p<span class="ot">&lt;-</span> <span class="fu">prop.table</span>(t)</span>
<span id="cb26-2"><a href="introduction-to-r.html#cb26-2" aria-hidden="true" tabindex="-1"></a>p</span></code></pre></div>
<pre><code>## marital
##          divorced legally separated           married     never married 
##       0.004045307       0.012135922       0.977346278       0.004854369 
##           unknown 
##       0.001618123</code></pre>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="introduction-to-r.html#cb28-1" aria-hidden="true" tabindex="-1"></a>p<span class="sc">*</span><span class="dv">100</span></span></code></pre></div>
<pre><code>## marital
##          divorced legally separated           married     never married 
##         0.4045307         1.2135922        97.7346278         0.4854369 
##           unknown 
##         0.1618123</code></pre>
</div>
<div id="ifelse" class="section level4 unnumbered">
<h4>ifelse()</h4>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="introduction-to-r.html#cb30-1" aria-hidden="true" tabindex="-1"></a>babies<span class="sc">$</span>first.preg<span class="ot">&lt;-</span> <span class="fu">with</span>(babies, <span class="fu">ifelse</span>(parity<span class="sc">==</span><span class="dv">0</span>, <span class="st">&#39;first&#39;</span>,<span class="st">&#39;not first&#39;</span>))</span>
<span id="cb30-2"><a href="introduction-to-r.html#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(babies<span class="sc">$</span>first.preg)</span></code></pre></div>
<pre><code>## 
##     first not first 
##       315       921</code></pre>
</div>
<div id="summary-mean-median-sd-quantile" class="section level4 unnumbered">
<h4>summary(), mean(), median(), sd(), quantile()</h4>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="introduction-to-r.html#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(babies)</span></code></pre></div>
<pre><code>##        id           date             gestation           wt       
##  Min.   :  15   Length:1236        Min.   :148.0   Min.   : 55.0  
##  1st Qu.:5286   Class :character   1st Qu.:272.0   1st Qu.:108.8  
##  Median :6730   Mode  :character   Median :280.0   Median :120.0  
##  Mean   :6001                      Mean   :279.3   Mean   :119.6  
##  3rd Qu.:7583                      3rd Qu.:288.0   3rd Qu.:131.0  
##  Max.   :9263                      Max.   :353.0   Max.   :176.0  
##                                    NA&#39;s   :13                     
##      parity            age              ed              ht       
##  Min.   : 0.000   Min.   :15.00   Min.   :0.000   Min.   :53.00  
##  1st Qu.: 0.000   1st Qu.:23.00   1st Qu.:2.000   1st Qu.:62.00  
##  Median : 1.000   Median :26.00   Median :2.000   Median :64.00  
##  Mean   : 1.932   Mean   :27.26   Mean   :2.916   Mean   :64.05  
##  3rd Qu.: 3.000   3rd Qu.:31.00   3rd Qu.:4.000   3rd Qu.:66.00  
##  Max.   :13.000   Max.   :45.00   Max.   :9.000   Max.   :72.00  
##                   NA&#39;s   :2                       NA&#39;s   :22     
##       wt1             dage            ded             dht            dwt       
##  Min.   : 87.0   Min.   :18.00   Min.   :0.000   Min.   :60.0   Min.   :110.0  
##  1st Qu.:114.8   1st Qu.:25.00   1st Qu.:2.000   1st Qu.:68.0   1st Qu.:155.0  
##  Median :125.0   Median :29.00   Median :4.000   Median :71.0   Median :170.0  
##  Mean   :128.6   Mean   :30.35   Mean   :3.189   Mean   :70.2   Mean   :171.2  
##  3rd Qu.:139.0   3rd Qu.:34.00   3rd Qu.:5.000   3rd Qu.:72.0   3rd Qu.:185.0  
##  Max.   :250.0   Max.   :62.00   Max.   :9.000   Max.   :78.0   Max.   :260.0  
##  NA&#39;s   :36      NA&#39;s   :7                       NA&#39;s   :492    NA&#39;s   :499    
##       inc            smoke             time            number     
##  Min.   :0.000   Min.   :0.0000   Min.   :0.0000   Min.   :0.000  
##  1st Qu.:2.000   1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:0.000  
##  Median :3.000   Median :1.0000   Median :1.0000   Median :1.000  
##  Mean   :3.701   Mean   :0.8681   Mean   :0.9625   Mean   :1.825  
##  3rd Qu.:5.000   3rd Qu.:1.0000   3rd Qu.:1.0000   3rd Qu.:3.000  
##  Max.   :9.000   Max.   :9.0000   Max.   :9.0000   Max.   :9.000  
##  NA&#39;s   :124                      NA&#39;s   :10       NA&#39;s   :10     
##      race             marital             drace               ddate      
##  Length:1236        Length:1236        Length:1236        Min.   : 1.00  
##  Class :character   Class :character   Class :character   1st Qu.: 8.00  
##  Mode  :character   Mode  :character   Mode  :character   Median :15.00  
##                                                           Mean   :15.37  
##                                                           3rd Qu.:23.00  
##                                                           Max.   :31.00  
##                                                                          
##      mdate            ydate           wtKg       macrosomia     
##  Min.   : 1.000   Min.   :1961   Min.   :1.562   Mode :logical  
##  1st Qu.: 4.000   1st Qu.:1961   1st Qu.:3.089   FALSE:1091     
##  Median : 7.000   Median :1962   Median :3.409   TRUE :145      
##  Mean   : 6.617   Mean   :1962   Mean   :3.397                  
##  3rd Qu.: 9.000   3rd Qu.:1962   3rd Qu.:3.722                  
##  Max.   :12.000   Max.   :1962   Max.   :5.000                  
##                                                                 
##  smallBaby                  birthWeightCat  preterm             whenBorn   
##  Mode :logical   Small baby        :  58   Mode :logical   Preterm  :  97  
##  FALSE:1178      Normal weight baby:1033   FALSE:1126      Full-term:1126  
##  TRUE :58        Large baby        : 145   TRUE :97        NA&#39;s     :  13  
##                                            NA&#39;s :13                        
##                                                                            
##                                                                            
##                                                                            
##   whiteRace          dwhiteRace                  smokeCat     smokeNow        
##  Length:1236        Length:1236        Never smoker  :544   Length:1236       
##  Class :character   Class :character   Past smoker   :198   Class :character  
##  Mode  :character   Mode  :character   Current smoker:484   Mode  :character  
##                                        NA&#39;s          : 10                     
##                                                                               
##                                                                               
##                                                                               
##               eduCat     first.preg       
##  HS graduate     :444   Length:1236       
##  HS+some college :298   Class :character  
##  College graduate:219   Mode  :character  
##  8th-12th grade  :183                     
##  HS+trade        : 65                     
##  (Other)         : 26                     
##  NA&#39;s            :  1</code></pre>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="introduction-to-r.html#cb34-1" aria-hidden="true" tabindex="-1"></a>gestAge<span class="ot">&lt;-</span> babies<span class="sc">$</span>gestation</span>
<span id="cb34-2"><a href="introduction-to-r.html#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(gestAge)</span></code></pre></div>
<pre><code>## [1] NA</code></pre>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="introduction-to-r.html#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(gestAge, <span class="at">na.rm=</span>T)</span></code></pre></div>
<pre><code>## [1] 279.3385</code></pre>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="introduction-to-r.html#cb38-1" aria-hidden="true" tabindex="-1"></a>gestAge<span class="ot">&lt;-</span> gestAge[<span class="fu">complete.cases</span>(gestAge)]</span>
<span id="cb38-2"><a href="introduction-to-r.html#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(gestAge)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   148.0   272.0   280.0   279.3   288.0   353.0</code></pre>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="introduction-to-r.html#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(gestAge)</span></code></pre></div>
<pre><code>## [1] 279.3385</code></pre>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="introduction-to-r.html#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">median</span>(gestAge)</span></code></pre></div>
<pre><code>## [1] 280</code></pre>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="introduction-to-r.html#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(gestAge)</span></code></pre></div>
<pre><code>## [1] 16.02769</code></pre>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="introduction-to-r.html#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">range</span>(gestAge)</span></code></pre></div>
<pre><code>## [1] 148 353</code></pre>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="introduction-to-r.html#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">min</span>(gestAge)</span></code></pre></div>
<pre><code>## [1] 148</code></pre>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="introduction-to-r.html#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">max</span>(gestAge)</span></code></pre></div>
<pre><code>## [1] 353</code></pre>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="introduction-to-r.html#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(gestAge)</span></code></pre></div>
<pre><code>##   0%  25%  50%  75% 100% 
##  148  272  280  288  353</code></pre>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="introduction-to-r.html#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(gestAge, <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="at">by =</span> <span class="fl">0.2</span>))</span></code></pre></div>
<pre><code>##   0%  20%  40%  60%  80% 100% 
##  148  270  277  283  290  353</code></pre>
</div>
<div id="round" class="section level4 unnumbered">
<h4>round()</h4>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="introduction-to-r.html#cb56-1" aria-hidden="true" tabindex="-1"></a>x<span class="ot">&lt;-</span> <span class="fl">1121.933384</span></span>
<span id="cb56-2"><a href="introduction-to-r.html#cb56-2" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(x, <span class="dv">3</span>)</span></code></pre></div>
<pre><code>## [1] 1121.933</code></pre>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="introduction-to-r.html#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(x, <span class="sc">-</span><span class="dv">2</span>)</span></code></pre></div>
<pre><code>## [1] 1100</code></pre>
</div>
<div id="paste" class="section level4 unnumbered">
<h4>paste()</h4>
<p>We can build up complex quoted strings with <code>paste</code>:</p>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="introduction-to-r.html#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">&quot;Mean (days) =&quot;</span>, <span class="fu">mean</span>(gestAge))</span></code></pre></div>
<pre><code>## [1] &quot;Mean (days) = 279.338511856092&quot;</code></pre>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="introduction-to-r.html#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">&quot;Mean (days) =&quot;</span>, <span class="fu">round</span>(<span class="fu">mean</span>(gestAge)))</span></code></pre></div>
<pre><code>## [1] &quot;Mean (days) = 279&quot;</code></pre>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="introduction-to-r.html#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">&#39;mean day (sd) = &#39;</span>, </span>
<span id="cb64-2"><a href="introduction-to-r.html#cb64-2" aria-hidden="true" tabindex="-1"></a>      <span class="fu">round</span>(<span class="fu">mean</span>(gestAge)), </span>
<span id="cb64-3"><a href="introduction-to-r.html#cb64-3" aria-hidden="true" tabindex="-1"></a>      <span class="st">&#39; (&#39;</span>, </span>
<span id="cb64-4"><a href="introduction-to-r.html#cb64-4" aria-hidden="true" tabindex="-1"></a>      <span class="fu">round</span>(<span class="fu">sd</span>(gestAge), <span class="dv">1</span>), </span>
<span id="cb64-5"><a href="introduction-to-r.html#cb64-5" aria-hidden="true" tabindex="-1"></a>      <span class="st">&#39;)&#39;</span>, </span>
<span id="cb64-6"><a href="introduction-to-r.html#cb64-6" aria-hidden="true" tabindex="-1"></a>      <span class="at">sep=</span><span class="st">&#39;&#39;</span>)</span></code></pre></div>
<pre><code>## [1] &quot;mean day (sd) = 279 (16)&quot;</code></pre>
</div>
<div id="apply" class="section level4 unnumbered">
<h4>apply()</h4>
<p>Carries out an operation on the rows or columns of a dataset. We pick the <code>MARGIN</code> to specify whether we want
this to be rows or columns</p>
<ul>
<li>1 = rows</li>
<li>2 = columns</li>
</ul>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="introduction-to-r.html#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">apply</span>(babies[, <span class="fu">c</span>(<span class="st">&#39;age&#39;</span>, <span class="st">&#39;dage&#39;</span>, <span class="st">&#39;wtKg&#39;</span>)], <span class="at">MARGIN =</span> <span class="dv">2</span>, <span class="at">FUN =</span> mean, <span class="at">na.rm=</span>T)</span></code></pre></div>
<pre><code>##      age     dage     wtKg 
## 27.25527 30.34825  3.39707</code></pre>
</div>
<div id="tapply" class="section level4 unnumbered">
<h4>tapply()</h4>
<p>Carries out an operation on one variable, split by a second variable (or group of variables) - e.g., means by group:</p>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="introduction-to-r.html#cb68-1" aria-hidden="true" tabindex="-1"></a>wt.by.smoke.term<span class="ot">&lt;-</span> <span class="fu">with</span>(babies, </span>
<span id="cb68-2"><a href="introduction-to-r.html#cb68-2" aria-hidden="true" tabindex="-1"></a>                       <span class="fu">tapply</span>(wt, <span class="fu">list</span>(smokeCat, whenBorn), mean, <span class="at">na.rm=</span>T))</span>
<span id="cb68-3"><a href="introduction-to-r.html#cb68-3" aria-hidden="true" tabindex="-1"></a>rw<span class="ot">&lt;-</span> <span class="fu">round</span>(wt.by.smoke.term, <span class="dv">1</span>)</span>
<span id="cb68-4"><a href="introduction-to-r.html#cb68-4" aria-hidden="true" tabindex="-1"></a>rw</span></code></pre></div>
<pre><code>##                Preterm Full-term
## Never smoker     107.0     124.1
## Past smoker      103.4     125.9
## Current smoker    91.7     116.2</code></pre>
</div>
</div>
<div id="user-defined-functions" class="section level3 unnumbered">
<h3>User Defined Functions</h3>
<p>You can write your own functions, text(arguments){ body }</p>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="introduction-to-r.html#cb70-1" aria-hidden="true" tabindex="-1"></a>custom.summary<span class="ot">&lt;-</span> <span class="cf">function</span>(x){</span>
<span id="cb70-2"><a href="introduction-to-r.html#cb70-2" aria-hidden="true" tabindex="-1"></a>  out<span class="ot">&lt;-</span> <span class="fu">paste</span>(<span class="fu">round</span>(<span class="fu">mean</span>(x, <span class="at">na.rm=</span>T), <span class="dv">2</span>), </span>
<span id="cb70-3"><a href="introduction-to-r.html#cb70-3" aria-hidden="true" tabindex="-1"></a>              <span class="st">&#39; (SD=&#39;</span>, </span>
<span id="cb70-4"><a href="introduction-to-r.html#cb70-4" aria-hidden="true" tabindex="-1"></a>              <span class="fu">round</span>(<span class="fu">sd</span>(x, <span class="at">na.rm=</span>T), <span class="dv">2</span>), </span>
<span id="cb70-5"><a href="introduction-to-r.html#cb70-5" aria-hidden="true" tabindex="-1"></a>              <span class="st">&#39;)&#39;</span>, </span>
<span id="cb70-6"><a href="introduction-to-r.html#cb70-6" aria-hidden="true" tabindex="-1"></a>              <span class="at">sep=</span><span class="st">&#39;&#39;</span>) </span>
<span id="cb70-7"><a href="introduction-to-r.html#cb70-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(out)</span>
<span id="cb70-8"><a href="introduction-to-r.html#cb70-8" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb70-9"><a href="introduction-to-r.html#cb70-9" aria-hidden="true" tabindex="-1"></a><span class="fu">custom.summary</span>(babies<span class="sc">$</span>age)</span></code></pre></div>
<pre><code>## [1] &quot;27.26 (SD=5.78)&quot;</code></pre>
</div>
<div id="saving-output-and-opening-in-word" class="section level3 unnumbered">
<h3>Saving output and opening in word</h3>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="introduction-to-r.html#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write.csv</span>(rw, <span class="st">&#39;test.csv&#39;</span>, <span class="at">quote=</span> F)</span></code></pre></div>
<p>Now open ‘test.csv’ with word. Highlight and click Table -&gt; convert text to table -&gt; ok.</p>
<div id="exercises-3" class="section level4 unnumbered">
<h4>Exercises (3)</h4>
<ol style="list-style-type: decimal">
<li>Create a function to summarize a binary (0/1 or FALSE/TRUE)) variable and return a character string that looks like, for example “18/54 (33.3%)”</li>
</ol>
<p>Framework</p>
<pre><code>bin.sum &lt;- function(x){
t &lt;- # tabulate x
n &lt;- # how many nonmissing observations?
x &lt;- # how many 1&#39;s?
pct &lt;- round()
paste()

}</code></pre>
<ol start="2" style="list-style-type: decimal">
<li>Use <code>tapply</code> to apply your function to the macrosomia using smokeCat as the grouping variable</li>
</ol>
<p>Hint</p>
<pre><code>result &lt;- tapply(X = 
                 INDEX= 
                 FUN=bin.sum)
        </code></pre>
<ol start="3" style="list-style-type: decimal">
<li><p>View your results as a Word table using by using write.csv to save to a CSV file.</p></li>
<li><p>[Advanced] Create a function to summarize a continuous variable in the following format: “Median (IQR.low, IQR.high), n.” Use <code>apply</code> to apply this function to the variables <code>age</code>, <code>dage</code>, ‘ht,’ ‘dht.’ The result should be a table that you can save in the same way as in question 3.</p></li>
<li><p>[More advanced] Use the function from question 4. to summarize a the variables <code>age</code>, <code>dage</code>, ‘ht,’ ‘dht’ in groups formed by ‘preterm.’ Hint: Look at the help for the function <code>aggregate</code>.</p></li>
</ol>
<p>Hint:</p>
<pre><code>aggregate(x=DATASET, 
          by=list(BY VARIABLES HERE), 
          FUN=FUNCTION.FROM.4)</code></pre>
<div id="exercises-3-solutions" class="section level5 unnumbered">
<h5>Exercises (3) solutions</h5>
<ol style="list-style-type: decimal">
<li></li>
<li></li>
<li></li>
<li></li>
<li></li>
</ol>
<div style="page-break-after: always;"></div>
</div>
</div>
</div>
</div>
<div id="working-with-more-than-one-dataset" class="section level2 unnumbered">
<h2>Working with more than one dataset</h2>
<p>Suppose you want to know how far from the average for the ethnic group each baby’s birth weight is as a Z-score:</p>
<pre><code>Z = (wt - average)/SD</code></pre>
<p>You need to</p>
<ol style="list-style-type: decimal">
<li>find the average and SD for each group</li>
<li>merge this data with the full babies dataset</li>
<li>calculate each baby’s Z score</li>
</ol>
<p>The R code for these steps is shown below</p>
<ol style="list-style-type: decimal">
<li>find the average and SD for each group and save it in a data.frame</li>
</ol>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="introduction-to-r.html#cb77-1" aria-hidden="true" tabindex="-1"></a>average.by.group <span class="ot">&lt;-</span> <span class="fu">tapply</span>(<span class="at">X =</span> babies<span class="sc">$</span>wtKg, </span>
<span id="cb77-2"><a href="introduction-to-r.html#cb77-2" aria-hidden="true" tabindex="-1"></a>                           <span class="at">INDEX=</span>babies<span class="sc">$</span>race, </span>
<span id="cb77-3"><a href="introduction-to-r.html#cb77-3" aria-hidden="true" tabindex="-1"></a>                           mean,<span class="at">na.rm=</span>T)</span>
<span id="cb77-4"><a href="introduction-to-r.html#cb77-4" aria-hidden="true" tabindex="-1"></a>                           </span>
<span id="cb77-5"><a href="introduction-to-r.html#cb77-5" aria-hidden="true" tabindex="-1"></a>sd.by.group <span class="ot">&lt;-</span> <span class="fu">tapply</span>(<span class="at">X =</span> babies<span class="sc">$</span>wtKg, </span>
<span id="cb77-6"><a href="introduction-to-r.html#cb77-6" aria-hidden="true" tabindex="-1"></a>                     <span class="at">INDEX=</span>babies<span class="sc">$</span>race, </span>
<span id="cb77-7"><a href="introduction-to-r.html#cb77-7" aria-hidden="true" tabindex="-1"></a>                     sd,<span class="at">na.rm=</span>T)</span>
<span id="cb77-8"><a href="introduction-to-r.html#cb77-8" aria-hidden="true" tabindex="-1"></a>stats <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">race=</span><span class="fu">names</span>(average.by.group),</span>
<span id="cb77-9"><a href="introduction-to-r.html#cb77-9" aria-hidden="true" tabindex="-1"></a>                    <span class="at">average=</span>average.by.group,</span>
<span id="cb77-10"><a href="introduction-to-r.html#cb77-10" aria-hidden="true" tabindex="-1"></a>                    <span class="at">SD=</span>sd.by.group)</span>
<span id="cb77-11"><a href="introduction-to-r.html#cb77-11" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(stats)               </span></code></pre></div>
<pre><code>##            race  average        SD
## asian     asian 3.137268 0.4543554
## black     black 3.216980 0.5422872
## mexican mexican 3.526989 0.4017935
## mixed     mixed 3.360719 0.5363923
## unknown unknown 3.892045        NA
## white     white 3.455721 0.5027514</code></pre>
<ol start="2" style="list-style-type: decimal">
<li>merge this data with the full babies dataset</li>
</ol>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb79-1"><a href="introduction-to-r.html#cb79-1" aria-hidden="true" tabindex="-1"></a>babies <span class="ot">&lt;-</span> <span class="fu">merge</span>(babies, </span>
<span id="cb79-2"><a href="introduction-to-r.html#cb79-2" aria-hidden="true" tabindex="-1"></a>                stats, </span>
<span id="cb79-3"><a href="introduction-to-r.html#cb79-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">by=</span><span class="st">&quot;race&quot;</span>)</span>
<span id="cb79-4"><a href="introduction-to-r.html#cb79-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb79-5"><a href="introduction-to-r.html#cb79-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(babies[ , <span class="fu">c</span>(<span class="st">&quot;wtKg&quot;</span>,<span class="st">&quot;average&quot;</span>, <span class="st">&quot;SD&quot;</span>,<span class="st">&quot;race&quot;</span>)])</span></code></pre></div>
<pre><code>##       wtKg  average        SD  race
## 1 3.409091 3.137268 0.4543554 asian
## 2 3.125000 3.137268 0.4543554 asian
## 3 2.642045 3.137268 0.4543554 asian
## 4 3.352273 3.137268 0.4543554 asian
## 5 2.982955 3.137268 0.4543554 asian
## 6 2.840909 3.137268 0.4543554 asian</code></pre>
<ol start="3" style="list-style-type: decimal">
<li>calculate each baby’s Z score</li>
</ol>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb81-1"><a href="introduction-to-r.html#cb81-1" aria-hidden="true" tabindex="-1"></a>babies<span class="sc">$</span>Z.wt <span class="ot">&lt;-</span> (babies<span class="sc">$</span>wtKg <span class="sc">-</span> babies<span class="sc">$</span>average)<span class="sc">/</span>babies<span class="sc">$</span>SD</span></code></pre></div>
<p>Finally, please save the alterations to the babies data set for the next session:</p>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb82-1"><a href="introduction-to-r.html#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write.csv</span>(babies, <span class="st">&#39;babiesAugmented.csv&#39;</span>, <span class="at">quote=</span>F, <span class="at">row.names =</span> F)</span></code></pre></div>
</div>
<div id="matrices" class="section level2 unnumbered">
<h2>Matrices</h2>
<p>A data structure useful in statistical programming and for more advanced data analysis is a matrix. A matrix is a 2-dimensional array, with rows and columns, that all contains items of the same type (as it is with vectors). We access their content using two indices (given the two dimensions).</p>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb83-1"><a href="introduction-to-r.html#cb83-1" aria-hidden="true" tabindex="-1"></a>M1 <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">12</span>,<span class="at">nrow=</span><span class="dv">3</span>,<span class="at">byrow =</span> F) </span>
<span id="cb83-2"><a href="introduction-to-r.html#cb83-2" aria-hidden="true" tabindex="-1"></a>M1a <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">12</span>,<span class="at">nrow=</span><span class="dv">3</span>,<span class="at">byrow =</span> T)    </span>
<span id="cb83-3"><a href="introduction-to-r.html#cb83-3" aria-hidden="true" tabindex="-1"></a>M2 <span class="ot">&lt;-</span> <span class="fu">matrix</span>(letters[<span class="dv">1</span><span class="sc">:</span><span class="dv">25</span>],<span class="at">nrow=</span><span class="dv">5</span>,<span class="at">ncol =</span> <span class="dv">5</span>) </span>
<span id="cb83-4"><a href="introduction-to-r.html#cb83-4" aria-hidden="true" tabindex="-1"></a>M3 <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(letters,LETTERS[<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>]),<span class="at">nrow=</span><span class="dv">5</span>,<span class="at">ncol =</span> <span class="dv">6</span>)   </span></code></pre></div>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb84-1"><a href="introduction-to-r.html#cb84-1" aria-hidden="true" tabindex="-1"></a>M3[<span class="dv">1</span>,<span class="dv">1</span>] </span></code></pre></div>
<pre><code>## [1] &quot;a&quot;</code></pre>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb86-1"><a href="introduction-to-r.html#cb86-1" aria-hidden="true" tabindex="-1"></a>M3[<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>,<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>] </span></code></pre></div>
<pre><code>##      [,1] [,2] [,3]
## [1,] &quot;a&quot;  &quot;f&quot;  &quot;k&quot; 
## [2,] &quot;b&quot;  &quot;g&quot;  &quot;l&quot; 
## [3,] &quot;c&quot;  &quot;h&quot;  &quot;m&quot;</code></pre>
</div>
<div id="lists" class="section level2 unnumbered">
<h2>Lists</h2>
<p>The most versatile data structure is the <code>list</code>. It can be used as a collection of different, even heterogeneous, objects. It can have one or many dimentions (e.g. list array). We need to access a list’s items using double square brackets <code>[[]]</code>.</p>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb88-1"><a href="introduction-to-r.html#cb88-1" aria-hidden="true" tabindex="-1"></a>some.stuff <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="at">first.matrix=</span>M1, </span>
<span id="cb88-2"><a href="introduction-to-r.html#cb88-2" aria-hidden="true" tabindex="-1"></a>                   <span class="at">second.matrix=</span>M2,    </span>
<span id="cb88-3"><a href="introduction-to-r.html#cb88-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">my.data.frame=</span>babies,    </span>
<span id="cb88-4"><a href="introduction-to-r.html#cb88-4" aria-hidden="true" tabindex="-1"></a>                   <span class="at">OldDads=</span>babies<span class="sc">$</span>dage <span class="sc">&gt;</span> <span class="dv">50</span>)    </span></code></pre></div>
<div class="sourceCode" id="cb89"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb89-1"><a href="introduction-to-r.html#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(some.stuff)   </span></code></pre></div>
<pre><code>## [1] &quot;list&quot;</code></pre>
<div class="sourceCode" id="cb91"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb91-1"><a href="introduction-to-r.html#cb91-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(some.stuff)  </span></code></pre></div>
<pre><code>## [1] 4</code></pre>
<div class="sourceCode" id="cb93"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb93-1"><a href="introduction-to-r.html#cb93-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(some.stuff)   </span></code></pre></div>
<pre><code>## [1] &quot;first.matrix&quot;  &quot;second.matrix&quot; &quot;my.data.frame&quot; &quot;OldDads&quot;</code></pre>
<div class="sourceCode" id="cb95"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb95-1"><a href="introduction-to-r.html#cb95-1" aria-hidden="true" tabindex="-1"></a>some.stuff[[<span class="dv">1</span>]] </span></code></pre></div>
<pre><code>##      [,1] [,2] [,3] [,4]
## [1,]    1    4    7   10
## [2,]    2    5    8   11
## [3,]    3    6    9   12</code></pre>
<div class="sourceCode" id="cb97"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb97-1"><a href="introduction-to-r.html#cb97-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(some.stuff[[<span class="st">&quot;OldDads&quot;</span>]])  </span></code></pre></div>
<pre><code>## 
## FALSE  TRUE 
##  1217    12</code></pre>
<div class="sourceCode" id="cb99"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb99-1"><a href="introduction-to-r.html#cb99-1" aria-hidden="true" tabindex="-1"></a>some.stuff<span class="sc">$</span>my.vector[<span class="dv">3</span>] </span></code></pre></div>
<pre><code>## NULL</code></pre>
<div class="sourceCode" id="cb101"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb101-1"><a href="introduction-to-r.html#cb101-1" aria-hidden="true" tabindex="-1"></a>some.stuff<span class="sc">$</span>my.data.frame<span class="sc">$</span>gestation[<span class="dv">41</span><span class="sc">:</span><span class="dv">45</span>]</span></code></pre></div>
<pre><code>## [1] 278 280 280 280 275</code></pre>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="assignments.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="references.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["Advanced HTA.pdf", "Advanced HTA.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
